site_name: Formal Verification
site_url: https://formalverification.io

nav:
  - Home: index.md

  - PhD Exams:
    - Algebra:
      - Groups: 
        - 1993 Nov: exams/groups/1993Nov.md
        - 1993 Nov: exams/groups/1993Nov.md
        - 1999 Mar: exams/groups/1999Mar.md
        - 2000 Nov: exams/groups/2000Nov10.md
        - 2002 Nov: exams/groups/2002Nov.md
        - 2003 Nov: exams/groups/2003Nov.md
        - 2004 Nov: exams/groups/2004Nov.md
        - 2006 Apr: exams/groups/2006Apr.md
        - 2006 Nov: exams/groups/2006Nov.md
        - 2007 Apr: exams/groups/2007Apr.md
        - 2008 Jan: exams/groups/2008Jan.md
        - 2008 Apr: exams/groups/2008Apr.md
      - Rings:
        - 1991 Nov: exams/real/1991Nov21.md
        - 1994 Nov: exams/real/1994Nov16.md
        - 1998 Apr: exams/real/1998Apr03.md
        - 2000 Nov: exams/real/2000Nov17.md
        - 2001 Nov: exams/real/2001Nov26.md
        - 2004 Apr: exams/real/2004Apr19.md
        - 2007 Nov: exams/real/2007Nov16.md
      - Fields: exams/fields/index.md
      - Linear Algebra: exams/linear-algebra/index.md
    - Analysis:
      - Real:
        - 1991 Nov: exams/real/1991Nov21.md
        - 1994 Nov: exams/real/1994Nov16.md
        - 1998 Apr: exams/real/1998Apr03.md
        - 2000 Nov: exams/real/2000Nov17.md
        - 2001 Nov: exams/real/2001Nov26.md
        - 2004 Apr: exams/real/2004Apr19.md
        - 2007 Nov: exams/real/2007Nov16.md
      - Complex:
        - 1991 Apr: exams/complex/1991Apr.md
        - 1991 Nov: exams/complex/1991Nov21.md
        - 1995 Apr: exams/complex/1995Apr10.md
        - 2001 Nov: exams/complex/2001Nov26.md
        - 2002 Nov: exams/complex/2002Nov20.md
        - 2003 Apr: exams/complex/2003Apr23.md
        - 2003 Nov: exams/complex/2003Nov17.md
        - 2004 Apr: exams/complex/2004Apr19.md
        - 2006 Nov: exams/complex/2006Nov13.md
        - 2007 Apr: exams/complex/2007Apr16.md
        - 2007 Nov: exams/complex/2007Nov16.md

  - Math Glossaries:
    - Logic & Foundations:
      - Models: models/model-theory-glossary.md
    - Algebra:
      - Groups: groups/group-theory-glossary.md
      - Rings: rings/ring-theory-glossary.md
      - Fields: fields/field-theory-glossary.md
    - Analysis:
      - Real: real/real-variables-glossary.md
      - Complex: complex/complex-variable-glossary.md

  - MkDocs doc:
    - MkDocs: mkdocs.md
    - Admonitions: mkdocs/admonitions.md
    - Diagrams: mkdocs/diagrams.md
    - Code blocks: mkdocs/code-blocks.md
    - Content tabs: mkdocs/content-tabs.md
    
  - About:
    - License: license.md

theme: 
  name: material
  features:
    - content.tooltips
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  font:
    text: Merriweather Sans
    code: Source Code Pro

  logo: img/cardano_we_logos/PNG/Cardano-RGB_Logo-Full-White.png

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
      
  - pymdownx.tabbed:
      alternate_style: true  
  - pymdownx.snippets
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/external-links.md
  - toc:
      permalink: "#"


watch:
  - includes

plugins:
  - search


extra:
  social:
    - icon: simple/github
      link: https://github.com/IntersectMBO/formal-ledger-specifications

